name:                plotwidget
version:             0.1.0.0
github:              "Vepnar/plotwidget"
license:             BSD-3-Clause
author:              "Arjan de Haan"
maintainer:          "example@example.com"
copyright:           "2025 Arjan de Haan"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Vepnar/plotwidget#readme>

dependencies:
- base >= 4.7 && < 5
- brick >= 2.8
- vector >= 0.13.2.0
- vty >= 6.0
- vty-crossplatform
- microlens-th
- microlens >= 0.3.0.0
- microlens-platform
- mtl
- text
- containers
- microlens-mtl
ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wmissed-specialisations
- -Wall-missed-specialisations

library:
  source-dirs: src

executables:
  animatedOverlay:
    main:                animatedOverlay.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - plotwidget
  mandlebrot:
    main:                mandlebrot.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - plotwidget
  wiener:
    main:                wiener.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - plotwidget
    - random-fu
    - random
    - mwc-random

tests:
  plotwidget-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - plotwidget
    - test-framework
    - HUnit
    - hspec
